"""End-to-end tests for the shift-handlers flow on a populated MTMainWindow.

test_07 already covers every helper in the mixin (format_offset_expr,
find_row_by_uid...). This file goes one level up: it drives the actual
``signalShiftApplied`` / ``signalShiftUndone`` Qt signals that the canvas
emits during an interactive drag, and asserts that:

- the x/y expressions on the corresponding model row receive the offset,
- the Alias column gets a shifted-alias so the user can tell the
  original row from the shifted one,
- undoing the same delta restores the original expressions and alias.

A silent break in this path means a user drags a signal on screen but
the signals table never reflects it — saving the workspace then loses
the shift entirely.
"""

import unittest

import numpy as np
import pandas as pd
from iplotDataAccess.appDataAccess import AppDataAccess
from iplotlib.core.canvas import Canvas
from iplotlib.core.impl_base import BackendParserBase
from iplotlib.interface.iplotSignalAdapter import AccessHelper

from mint.gui.mtMainWindow import MTMainWindow
from mint.models.accessModes.mtGeneric import MTGenericAccessMode
from mint.models.utils import mtBlueprintParser
from mint.tests.fixtures import write_csv_datasource_config
from mint.tests.qAppSingleton import ensure_qapp


PULSE_ID = 'ITER:MCTB-TEST/111'


def _build_main_window(impl: str = 'matplotlib') -> MTMainWindow:
    canvas = Canvas()
    time_model = {"range": {}}
    data_sources = AccessHelper.da.get_connected_data_source_names()
    win = MTMainWindow(
        canvas, AccessHelper.da, time_model, app_version='test',
        data_sources=data_sources,
        blueprint=mtBlueprintParser.DEFAULT_BLUEPRINT, impl=impl)
    win.dataRangeSelector.import_dict({
        'mode': MTGenericAccessMode.PULSE_NUMBER,
        'pulse_nb': [PULSE_ID],
        'base': 'Second(s)',
        't_start': '-5',
        't_end': '4',
    })
    return win


def _populate_and_draw(win: MTMainWindow, alias: str = 'alpha') -> str:
    """Populate the signals table with a single CSV signal, draw and return
    the signal's uid (the ROWUID_COLNAME generated by the model)."""
    df = pd.DataFrame({
        'DS': ['csv'],
        'Variable': ['MAG-MCTB-F1:VAR1'],
        'Stack': ['1.1'],
        'Plot type': ['PlotXY'],
        'Alias': [alias],
    })
    win.sigCfgWidget.model.set_dataframe(df)
    win.draw_clicked()
    # The set_dataframe path fills ROWUID_COLNAME for any newly-inserted row.
    dataframe = win.sigCfgWidget.model.get_dataframe()
    uid_col = win.sigCfgWidget.model.ROWUID_COLNAME
    return dataframe.at[0, uid_col]


class ShiftAppliedUpdatesModelTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.app = ensure_qapp()
        cls.cfg_path = write_csv_datasource_config()
        AppDataAccess.initialize(cls.cfg_path)
        AccessHelper.da = AppDataAccess.get_data_access()

    def test_apply_sets_y_offset_expression_on_row(self):
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win)

            # Simulate a vertical drag of +2.5 — the same payload the canvas
            # would emit via signalShiftApplied.
            win._on_signal_shift_applied(uid, 0.0, 2.5, 'inline')

            df = win.sigCfgWidget.model.get_dataframe()
            self.assertIn('+ 2.5', df.at[0, 'y'])
            # x was not touched — no offset expected.
            self.assertNotIn('+', df.at[0, 'x'] or '')
        finally:
            win.close()

    def test_apply_sets_shifted_alias_on_row(self):
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win)
            win._on_signal_shift_applied(uid, 0.0, 1.0, 'inline')

            df = win.sigCfgWidget.model.get_dataframe()
            new_alias = df.at[0, 'Alias']
            # Alias must change from the original "alpha" to a
            # shifted-variant so the user can tell them apart.
            self.assertNotEqual(new_alias, 'alpha')
            self.assertTrue(new_alias)
        finally:
            win.close()

    def test_apply_then_undo_restores_original_expressions(self):
        """Apply +3 then undo -3 (the reverse delta) → row should be back to
        its original x/y expressions and alias."""
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win)
            original_y = win.sigCfgWidget.model.get_dataframe().at[0, 'y']

            win._on_signal_shift_applied(uid, 0.0, 3.0, 'inline')
            win._on_signal_shift_undone(uid, 0.0, 3.0, 'inline')

            df = win.sigCfgWidget.model.get_dataframe()
            # After the full undo, the accumulated delta is 0 so the
            # expression collapses back to the original.
            self.assertEqual(df.at[0, 'y'], original_y)
            self.assertEqual(df.at[0, 'Alias'], 'alpha')
        finally:
            win.close()

    def test_apply_accumulates_subsequent_drags(self):
        """Two drags of +1 each should produce a single offset of +2, not
        two separate +1 layers stacked on top of each other."""
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win)

            win._on_signal_shift_applied(uid, 0.0, 1.0, 'inline')
            win._on_signal_shift_applied(uid, 0.0, 1.0, 'inline')

            df = win.sigCfgWidget.model.get_dataframe()
            self.assertIn('+ 2.0', df.at[0, 'y'])
        finally:
            win.close()

    def test_undo_restores_the_label_of_a_row_without_alias(self):
        """Without alias the legend shows the variable name; undoing the
        shift must bring that name back, not the row's empty alias."""
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win, alias='')
            signal, _ = win._find_signal_in_canvas(uid)
            label = signal.label

            win._on_signal_shift_applied(uid, 0.0, 3.0, 'inline')
            self.assertNotEqual(signal.label, label)
            win._on_signal_shift_undone(uid, 0.0, 3.0, 'inline')

            self.assertEqual(signal.label, label)
            self.assertEqual(win.sigCfgWidget.model.get_dataframe().at[0, 'Alias'], '')
        finally:
            win.close()

    def test_undoing_large_offsets_restores_the_alias(self):
        """Undoing every shift restores the alias even when adding and then
        subtracting the offsets does not give back exactly 0.0."""
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win)
            original_y = win.sigCfgWidget.model.get_dataframe().at[0, 'y']

            for dy in (1234567.8, 2345678.9):
                win._on_signal_shift_applied(uid, 0.0, dy, 'inline')
            for dy in (2345678.9, 1234567.8):
                win._on_signal_shift_undone(uid, 0.0, dy, 'inline')

            df = win.sigCfgWidget.model.get_dataframe()
            self.assertEqual(df.at[0, 'Alias'], 'alpha')
            self.assertEqual(df.at[0, 'y'], original_y)
        finally:
            win.close()

    def test_auto_refresh_drops_the_undo_history(self):
        """The auto-refresh rebuilds the canvas the way Draw does: the shift
        stays in the row and there is nothing left to undo, since undoing on
        the replaced canvas would draw its old signal again."""
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win)
            qt_canvas = win.canvasStack.currentWidget()
            signal, _ = win._find_signal_in_canvas(uid)
            impl_plot = qt_canvas._parser._signal_impl_plot_lut.get(uid)
            qt_canvas._start_drag_shift(impl_plot, signal, 0.0, is_datetime=True)
            qt_canvas._end_drag_shift(2.5)
            self.assertTrue(qt_canvas.can_undo())

            win.on_timeout()

            self.assertFalse(qt_canvas.can_undo())
            self.assertIn('+ 2.5', win.sigCfgWidget.model.get_dataframe().at[0, 'y'])
        finally:
            win.close()

    @staticmethod
    def _duplicate(win, uid, dy):
        """Apply Shift with 'Duplicate signal' ticked in the DIST dialog."""
        signal, _ = win._find_signal_in_canvas(uid)
        win._on_signal_shift_requested(uid, signal.name, signal.data_source,
                                       str(signal.pulse_nb), 0.0, dy, True)
        return signal

    def test_duplicate_adds_a_shifted_row_that_undo_removes(self):
        """The copy is a row of its own, for the pulse that was picked, and it
        goes away on undo and comes back on redo."""
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win, alias='')
            self._duplicate(win, uid, 2.5)

            df = win.sigCfgWidget.model.get_dataframe()
            self.assertEqual(df.at[0, 'Alias'], '')
            self.assertTrue(df.at[1, 'Alias'].startswith('shifted_'))
            self.assertIn('+ 2.5', df.at[1, 'y'])
            self.assertEqual(df.at[1, 'PulseId'], PULSE_ID)
            copy_alias = df.at[1, 'Alias']

            win.undo()
            self.assertNotIn(copy_alias, win.sigCfgWidget.model.get_dataframe()['Alias'].tolist())

            win.redo()
            self.assertEqual(win.sigCfgWidget.model.get_dataframe().at[1, 'Alias'], copy_alias)
        finally:
            win.close()

    @unittest.skipUnless(hasattr(BackendParserBase, 'add_signal'),
                         "drawing the copy needs an iplotlib with add_signal")
    def test_duplicate_is_drawn_at_once_and_undo_takes_it_off(self):
        win = _build_main_window()
        try:
            uid = _populate_and_draw(win, alias='')
            plot = win.canvas.plots[0][0]
            original = self._duplicate(win, uid, 2.5)

            copy_alias = win.sigCfgWidget.model.get_dataframe().at[1, 'Alias']
            self.assertEqual([s.label for s in plot.signals[1]], [original.label, copy_alias])
            np.testing.assert_allclose(plot.signals[1][1].y_data, np.asarray(original.y_data) + 2.5)

            win.undo()
            self.assertEqual([s.label for s in plot.signals[1]], [original.label])

            win.redo()
            self.assertEqual([s.label for s in plot.signals[1]], [original.label, copy_alias])
        finally:
            win.close()


if __name__ == '__main__':
    unittest.main()
